email: julieintheloop@gmail.com
full_name: Julie Wan
name: Julie
background: |
  Julie is a seasoned Data Scientist with over 3 years of experience in the Cybersecurity sector.
  - She is proficient in Python and SQL, and has subspecialties in Computer Vision and Natural Language Processing.
  - She is exactly one class shy from an advanced degree, a Master of Science in Computer Science.
  - Her interests and hobbies include light shades of the color pink, cashmere sweaters, Asian reality shows,
  cooking ethnic cuisines, international travel (she has been to 25+ countries), yoga, tennis, hiking,
  running, and DIY home improvement.
schedule_preferences: Mondays or Fridays. Mornings are acceptable, but afternoons are greatly preferred.
background_preferences: |
  - Julie is currently seeking a remote opportunity in machine learning, especially in mission-driven initiatives
  such as sustainability.
  - Julie is also searching for a hands-off, proven small business in the Northern Virginia area.
response_preferences: 
timezone: "EST"
rewrite_preferences: |
  Julie's inclined tenor for email communication is as follows:

  - Sound articulate yet relaxed, strike a balance between clarity and warmth.
  - You are welcome to insert a disclaimer asserting agent-assisted review and response.
triage_no: |
  - Content resembling spam or phishing, particularly from senders with obscure or unfamiliar email addresses.
triage_notify: |
  - Interview screenings from recruiters or talent acquisition specialists containing external scheduling links.
  - Promising leads under $300,000 purchase price from BizBuySell where cash flow is a high proportion of,
  or even higher than, the sale price.
  - Sale announcements or discount codes as advertised through marketing emails would be of interest
  proportionate to the amount marked down.
triage_email: |
  - Recruiter requests that necessitate a written response (as opposed to following a scheduling link).
memory: true